plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
env:
  browser: true
  es2021: true
extends: 
  - 'airbnb-base'
  - 'plugin:jest/recommended'
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  #  "import/no-extraneous-dependencies": ["error", {"projectDependencies": false}]
  #  'import/no-extraneous-dependencies': ['error', {projectDependencies: true}]
   "import/no-extraneous-dependencies": "off"
   'linebreak-style': ["error", "unix"]
  #  'linebreak-style': ["error", "windows"]
   import/extensions:
    - error
    - ignorePackages
    - js: always
   no-console: 0
   no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
   no-return-assign: 0
   no-restricted-syntax: 0
   
   